# Autogenerated wrapper script for libpostal_jll for i686-linux-gnu-cxx03
export libpostal

JLLWrappers.@generate_wrapper_header("libpostal")
JLLWrappers.@declare_library_product(libpostal, "libpostal.so.1")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpostal,
        "lib/libpostal.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
